// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8gfVaq7bylweruNOtC4rroFs1OUVF2jE',
    appId: '1:43894038079:android:759283abe004154f0ce28a',
    messagingSenderId: '43894038079',
    projectId: 'food-delivery-f5251',
    storageBucket: 'food-delivery-f5251.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0X7JJJReeoX3ugDUxn-ER0I66DPLP1Ag',
    appId: '1:43894038079:ios:bd1421585601b42f0ce28a',
    messagingSenderId: '43894038079',
    projectId: 'food-delivery-f5251',
    storageBucket: 'food-delivery-f5251.firebasestorage.app',
    iosClientId: '43894038079-aiu3jh2a71jr4oka3fpmr6vgcuk6v0tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtlplx6n1EhopwnSfYokXVXcLgWc12P34',
    appId: '1:43894038079:web:b427c0f9d7520da20ce28a',
    messagingSenderId: '43894038079',
    projectId: 'food-delivery-f5251',
    authDomain: 'food-delivery-f5251.firebaseapp.com',
    storageBucket: 'food-delivery-f5251.firebasestorage.app',
    measurementId: 'G-5RSLZLL8E9',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtlplx6n1EhopwnSfYokXVXcLgWc12P34',
    appId: '1:43894038079:web:615b9925033b47e70ce28a',
    messagingSenderId: '43894038079',
    projectId: 'food-delivery-f5251',
    authDomain: 'food-delivery-f5251.firebaseapp.com',
    storageBucket: 'food-delivery-f5251.firebasestorage.app',
    measurementId: 'G-56GJ55WKD0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0X7JJJReeoX3ugDUxn-ER0I66DPLP1Ag',
    appId: '1:43894038079:ios:bd1421585601b42f0ce28a',
    messagingSenderId: '43894038079',
    projectId: 'food-delivery-f5251',
    storageBucket: 'food-delivery-f5251.firebasestorage.app',
    iosClientId: '43894038079-aiu3jh2a71jr4oka3fpmr6vgcuk6v0tj.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodDeliveryApp',
  );

}